version: '3.8'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mern-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: frontend-react
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-express
    expose:
      - "5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - ATLAS_URI=${ATLAS_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-5000}
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge