# .azure/aci-deployment.template.yml
# Variables like ${VAR_NAME} will be replaced by envsubst in the GitHub Action
apiVersion: '2021-10-01' # Use a recent, stable API version
location: ${ACI_LOCATION} # e.g., eastus
name: ${ACI_CONTAINER_GROUP_NAME} # e.g., azuretriall-app-group
properties:
  containers:
  - name: azuretriall-frontend
    properties:
      image: ${REGISTRY_LOGIN_SERVER}/azuretriall-frontend:latest # Or use github.sha for versioning
      ports:
      - port: 3000 # Internal port for the frontend (React app)
        protocol: TCP
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5

  - name: azuretriall-backend
    properties:
      image: ${REGISTRY_LOGIN_SERVER}/azuretriall-backend:latest # Or use github.sha
      ports:
      - port: 5000 # Internal port for the backend (Node.js app)
        protocol: TCP
      environmentVariables:
      - name: 'ATLAS_URI'
        value: '${ATLAS_URI}' # This will be substituted
      - name: 'PORT' # Your server.js uses process.env.PORT
        value: '5000'
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5

  - name: azuretriall-nginx
    properties:
      image: ${REGISTRY_LOGIN_SERVER}/azuretriall-nginx:latest # Or use github.sha
      ports:
      - port: 80 # Publicly exposed port for the group
        protocol: TCP
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 0.5
      # Nginx (with the updated config) will now proxy to:
      # Frontend: http://localhost:3000
      # Backend: http://localhost:5000/api/

  osType: Linux
  restartPolicy: OnFailure
  ipAddress:
    type: Public
    ports:
    - port: 80 # Make port 80 of the Nginx container public
      protocol: TCP
    dnsNameLabel: ${DNS_NAME_LABEL} # e.g., azuretriall-app-${{ github.run_id }}
  imageRegistryCredentials: # ACR credentials for pulling images
    - server: ${REGISTRY_LOGIN_SERVER}
      username: ${REGISTRY_USERNAME}
      password: ${REGISTRY_PASSWORD} # The actual password, handled by GitHub Actions secrets
tags:
  appName: "AzureTriall"
  repo: "sairevanth0007/azuretriall"
  # Add any other relevant tags