name: Deploy MERN App to Azure (Windows)

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  # Deploy Backend (Node.js Server)
  deploy-server:
    runs-on: windows-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Server Dependencies
        run: |
          cd server
          npm install

      - name: Build Server (if needed)
        run: |
          cd server
          npm run build  # Optional if using plain JS without transpilation

      - name: Deploy to Azure App Service (Server)
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_AZURE_SERVER_APP_NAME
          slot-name: production
          publish-profile: ${{ secrets.AZURE_SERVER_PUBLISH_PROFILE }}
          package: .\server  # Use Windows-style path

      - name: Configure Environment Variables
        uses: azure/appservice-settings@v1
        with:
          app-name: YOUR_AZURE_SERVER_APP_NAME
          slot-name: production
          app-settings-json: |
            [
              {
                "name": "ATLAS_URI",
                "value": "${{ secrets.ATLAS_URI }}",
                "slotSetting": false
              },
              {
                "name": "PORT",
                "value": "5000",
                "slotSetting": false
              }
            ]

  # Deploy Frontend (React Client)
  deploy-client:
    runs-on: windows-latest
    environment: production
    needs: deploy-server  # Ensure server is deployed first

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Client Dependencies
        run: |
          cd client
          npm install

      - name: Build React App
        run: |
          cd client
          npm run build

      - name: Deploy to Azure App Service (Client)
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_AZURE_CLIENT_APP_NAME
          slot-name: production
          publish-profile: ${{ secrets.AZURE_CLIENT_PUBLISH_PROFILE }}
          package: .\client\build  # Use Windows-style path

      - name: Configure Environment Variables for Client
        uses: azure/appservice-settings@v1
        with:
          app-name: YOUR_AZURE_CLIENT_APP_NAME
          slot-name: production
          app-settings-json: |
            [
              {
                "name": "REACT_APP_API_URL",
                "value": "https://${{ secrets.AZURE_SERVER_APP_NAME }}.azurewebsites.net",
                "slotSetting": false
              }
            ]