name: Deploy Azuretrall App with Nginx to Azure

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 4. Build and Push All Images to ACR
      - name: Build and Push Docker Images
        uses: azure/docker-compose-build-push-action@v1
        with:
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group: my-resource-group
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          compose-file-path: "docker-compose.yml"

      # 5. Deploy to Azure Container Instances (ACI) via Docker Compose
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Entire Stack to Azure
        run: |
          az container compose create \
            --resource-group my-resource-group \
            --name azuretriall-app \
            --file docker-compose.yml \
            --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --dns-name-label azuretriall-${{ github.run_id }}